language: java
jdk:
- openjdk8
branches:
  only:
  - master
  - /^v[0-9]+\.[0-9]+\.[0-9]+.*/
script: "./build.sh"
env:
  global:
  - secure: gUSz1xb39dmYYA74RIwpj0fOO4YF8sELMIsPYyDSaQU91FuW9TUEEmggCdNIaJD3MDij0JldKQAkrvKXs2C03uzOAUxYnnmiBwTRKUVhFMc1BYiH+HEiGe0nSdIBPu9YTM2iEgLvLUk5EPYSbtwZ0Sxa/W2MSpKKXTi6q4N5p6o1c6BJPMZRhPIPcJAKeww0en8+jvjY8ScynuchfvjasOw55W5DHEpfR9ltpqDpRSTWj5SmsWTM04NOJ6GUncAe1lIcsukH/cSL34OdNZepqz6H1XVL8mVJyoWlexs0ZnbyzFal+h0WfOaIO5QuWk39gcweLd9obEMvvSXA3RFdeHDLWYdjWi2b4kAwPZ5kn0VyBdG1VjXycyMu8BINUftVSmtKEYy7Hb6hPx99tZllPXY8UQxhqfPgqYxdk8+ky29AjJUW9r6VV8rcnUHP1qNewZKZI27DoM/dwnOT16QD71dEV57RJqq37ZumobopeJHf4YRZBqZxpDTdKKrk3gZVXrqnjfKCS6fhqLv3RxiXCrC5I8K4mdOk76/2aLglh4DpdeZP7k1k+Wa+SaHy/4GMxKSg+hD9R4iBOgV4BrGHLuP1VbFJtQ4R8OiCSf/VhtJAJEUcwzNtjUaf+1kJhNENrXzUvl+WYNekI9sOawKLQ46BtYjj03ADYkR/5d5zxxE=
  - secure: iJi/9svLESjBr686u70FN14cKr383Ck2eI5+RdpT0qVmgBGp7H4dd+mYnrdPr+ISxfbrKGDgyykO3FbpH/aTVRvaGYJwQCFF686TsazUYI7T8biGj4LRKwFnRmXQSmqVGVgbFBX/mWn2qd2WpIMudKYesGhsSWSSl+bWT2aBoMZXHpcFepJL8Kxq3oQmESzpQ8M+ADIP5nMDblH87gVmKKGOSScf9GLbSTFhRXntgQ1ROY7wnjQtZtVxf+pVMCQtxfEA/LnR9OzB8/wG3iuYADp8f0hVNu4U+88GAHD43VgMvO04OH13+bR/d7E3Iy3dQrCOpHoQkKimwBijEUk5Q4Qvzox6oaHL4aW8A8iSXoy8fHt1t/TXgWogtubJ3SfZTKxu/vir6DjotAQdHRoOyfdbdXWMdpCDU+GjMq7ufGdnGCEDlAcP3LYEZUED376QRuxLyMepqJFameNB3qXAesUIUJkBiKV0JyiIBkp6jVwotQFOFkDRc4/s7ia8MougxakXgsY498XMKTmqFI70zOFksOKU789iGJyGRudjMifXRN9yv2qEZLcmH+OmgfkG5Q8NfBab2T2Itsg0NpZ7ynAmF3ffxab+l7B39P9AFXr9vIsdEzi2etBRtFhYJQxijnH2yNocddNVZUvU/ZRZbxGSwtRfG9HWcIgBNl1PXTc=
