name: Deploy

on:
  push:
    branches:
      - master
      - feature/GitlabActions
    tags:
      -v*


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup GPG key
        shell: bash
        env:
          GPG_KEY: ${{ secrets.GPG_KEY }}
        run:
          echo -e $GPG_KEY | gpg -vv --import --batch --yes
      - name: Deploy
        shell: bash
        env:
          CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
          CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
        run:
          mvn deploy -P sign-artifacts --settings ./settings.xml --file pom.xml